#!/bin/sh

die() {
    printf -- "$@\n" 1>&2
    exit 1
}

helpdie() {
    printhelp 1>&2
    exit 1
}

needcmd() {
    command -v "$1" 2>&1 > /dev/null || die "Error: command '$1' not found"
}

printhelp() {
    printf "$0 <inFile> [-b sampleRate]\n"
}

getformat() {
    e="$(printf I | od -to2 | head -n1 | cut -f2 -d" " | cut -c6)"
    if [ "$e" = "0" ] ; then
        printf "float_be"
    else
        printf "float_le"
    fi
}

needcmd aplay
needcmd sndc
needcmd lscpu

if [ -z "$1" ] ; then
    helpdie
fi

FILE="$1"
shift

if [ "$1" = "-b" ] ; then
    if [ -z "$2" ] ; then
        helpdie
    fi
    BR="$2"
else
    BR="44100"
fi

FORMAT="$(getformat)"

(sleep 0.1 && sndc "$FILE") | aplay -R 100 -c 1 -t raw -r "$BR" -f "$FORMAT"
